version: "3.9"

services:
  keycloak:
    volumes:
      - ./imports:/opt/jboss/keycloak/imports
    image: quay.io/keycloak/keycloak
    container_name: keycloak
    ports:
      - "8080:8080"
    network_mode: "bridge"
    environment:
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: Pa55w0rd
    command:
      - "-Dkeycloak.migration.action=import"
      - "-Dkeycloak.migration.provider=dir"
      - "-Dkeycloak.migration.dir=/opt/jboss/keycloak/imports/"
      - "-Dkeycloak.migration.strategy=OVERWRITE_EXISTING"
      - start-dev

  booking_service:
    build:
      context: .
      dockerfile: ./booking_service/Dockerfile
    container_name: booking_service
    ports:
      - "8000:8000"
    network_mode: "bridge"
    hostname: booking_service
    environment:
      - AMQP_URL=amqp://guest:guest123@51.250.26.59:5672/
      - ROOM_SERVICE_URL=http://172.17.0.1:8001/api
      - POSTGRES_DRIVERNAME=postgresql
      - POSTGRES_USER=secUREusER
      - POSTGRES_PASSWORD=StrongEnoughPassword)
      - POSTGRES_HOST=51.250.26.59
      - POSTGRES_PORT=5432
      - POSTGRES_DATABASE=booking_service
      - SERVICE_PORT=8000
      - KEYCLOAK_URL=http://172.17.0.1:8080/
      - KEYCLOAK_CLIENT_ID=booking-service
      - KEYCLOAK_REALM=MyRealm
      - KEYCLOAK_CLIENT_SECRET=**********

  room_service:
    build:
      context: .
      dockerfile: ./room_service/Dockerfile
    container_name: room_service
    ports:
      - "8001:8001"
    network_mode: "bridge"
    hostname: room_service
    environment:
      - AMQP_URL=amqp://guest:guest123@51.250.26.59:5672/
      - POSTGRES_DRIVERNAME=postgresql
      - POSTGRES_USER=secUREusER
      - POSTGRES_PASSWORD=StrongEnoughPassword)
      - POSTGRES_HOST=51.250.26.59
      - POSTGRES_PORT=5432
      - POSTGRES_DATABASE=room_service
      - SERVICE_PORT=8001