version: "3.10"

services:
  booking_service:
    build:
      context: .
      dockerfile: ./booking_service/Dockerfile
    container_name: booking_service
    ports:
      - "8000:8000"
    network_mode: "bridge"
    hostname: booking_service
    environment:
      - AMQP_URL=amqp://guest:guest@172.17.0.1:5672/
      - ROOM_SERVICE_URL=http://172.17.0.1:8001/api
      - PORT=8000
      - POSTGRES_DRIVERNAME=postgresql
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=mysecretpassword2
      - POSTGRES_HOST=localhost
      - POSTGRES_PORT=5433
      - POSTGRES_DATABASE=booking_database

  room_service:
    build:
      context: .
      dockerfile: ./room_service/Dockerfile
    container_name: room_service
    ports:
      - "8001:8001"
    network_mode: "bridge"
    hostname: room_service
    environment:
      - AMQP_URL=amqp://guest:guest@172.17.0.1:5672/
      - POSTGRES_URL=postgresql://postgres:mysecretpassword@172.17.0.1:5432/room_database
      - PORT=8001