version: "3.9"

services:
  keycloak:
    volumes:
      - ./imports:/opt/jboss/keycloak/imports
    image: quay.io/keycloak/keycloak
    container_name: keycloak
    ports:
      - "8080:8080"
    networks:
      - app-network
    environment:
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: Pa55w0rd
    command:
      - "-Dkeycloak.migration.action=import"
      - "-Dkeycloak.migration.provider=dir"
      - "-Dkeycloak.migration.dir=/opt/jboss/keycloak/imports/"
      - "-Dkeycloak.migration.strategy=OVERWRITE_EXISTING"
      - start-dev

  booking_service:
    build:
      context: .
      dockerfile: ./booking_service/Dockerfile
    container_name: booking_service
    ports:
      - "8000:8000"
    networks:
      - app-network
    hostname: booking_service
    environment:
      - AMQP_URL=amqp://guest:guest123@51.250.26.59:5672/
      - ROOM_SERVICE_URL=http://room_service:8001/api
      - POSTGRES_DRIVERNAME=postgresql
      - POSTGRES_USER=secUREusER
      - POSTGRES_PASSWORD=StrongEnoughPassword)
      - POSTGRES_HOST=51.250.26.59
      - POSTGRES_PORT=5432
      - POSTGRES_DATABASE=booking_service
      - SERVICE_PORT=8000
      - KEYCLOAK_URL=http://keycloak:8080/
      - KEYCLOAK_CLIENT_ID=booking-service
      - KEYCLOAK_REALM=MyRealm
      - KEYCLOAK_CLIENT_SECRET=**********

  room_service:
    build:
      context: .
      dockerfile: ./room_service/Dockerfile
    container_name: room_service
    ports:
      - "8001:8001"
#    network_mode: "bridge"
    networks:
      - app-network
    hostname: room_service
    environment:
      - AMQP_URL=amqp://guest:guest123@51.250.26.59:5672/
      - POSTGRES_DRIVERNAME=postgresql
      - POSTGRES_USER=secUREusER
      - POSTGRES_PASSWORD=StrongEnoughPassword)
      - POSTGRES_HOST=51.250.26.59
      - POSTGRES_PORT=5432
      - POSTGRES_DATABASE=room_service
      - SERVICE_PORT=8001

  loki:
    image: grafana/loki:latest
    container_name: loki
    ports:
      - "3100:3100"
    networks:
      - app-network
    command: -config.file=/etc/loki/local-config.yaml

  promtail:
    image: grafana/promtail:latest
    container_name: promtail
    volumes:
      - ./docker-config.yaml:/etc/promtail/docker-config.yaml
      - /var/log:/var/log
      - /var/lib/docker/containers:/var/lib/docker/containers
    networks:
      - app-network
    command: -config.file=/etc/promtail/docker-config.yaml

  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    ports:
      - "3000:3000"
    networks:
      - app-network
    environment:
      - GF_EXPLORE_ENABLED=true
    volumes:
      - ./grafana-storage:/var/lib/grafana

  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
      - ./alert.yml:/etc/prometheus/alert.yml
    ports:
      - "9090:9090"
    networks:
      - app-network
    links:
      - alertmanager:alertmanager
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
      - '--storage.tsdb.max-block-duration=30m'
      - '--storage.tsdb.min-block-duration=30m'
      - '--web.enable-lifecycle'
      - '--web.console.libraries=/usr/share/prometheus/console_libraries'
      - '--web.console.templates=/usr/share/prometheus/consoles'

  node:
    image: prom/node-exporter:latest
    container_name: node
    ports:
      - "9100:9100"
    networks:
      - app-network
    volumes:
      - /proc:/host/proc:ro
      - /sys:/host/sys:ro
      - /:/rootfs:ro

  alertmanager:
    image: prom/alertmanager:v0.26.0
    container_name: alertmanager
    ports:
      - "9093:9093"
    volumes:
      - ./alertmanager.yml:/etc/alertmanager/alertmanager.yml
    restart: always
    networks:
      - app-network
    command:
      - '--config.file=/etc/alertmanager/alertmanager.yml'
      - '--storage.path=/alertmanager'

networks:
  app-network:
    driver: bridge

volumes:
  prometheus:
    name: prometheus
  grafana-storage:
    driver: local